#! /usr/bin/env bash

if [ -z "${1}" ] ;  then
    print "No instruction provided"
fi

if [ "${1}" == "build-image" ] ; then
   docker build -t so-2023-1-gcc .
   exit 0
fi

if [ "${1}" == "compile" ] ; then
   docker run --rm -v $PWD:/app -w /app so-2023-1-gcc gcc -Wall -Werror -o practica01 src/*.c
   exit 0
fi

if [ "${1}" == "run" ] ; then
   docker run --rm -v $PWD:/app -w /app so-2023-1-gcc ./practica01 "${2}"
   exit 0
fi

if [ "${1}" == "clean" ] ; then
   docker run --rm -v $PWD:/app -w /app so-2023-1-gcc rm practica01
   exit 0
fi

if [ "${1}" == "test" ] ; then
   docker run --rm -v $PWD:/app -w /app so-2023-1-gcc sh run-tests
   exit 0
fi

docker run --rm -v $PWD:/app -w /app so-2023-1-gcc ${1}
