#! /usr/bin/env sh

ERRORS=""
COUNTER=0
TOTAL_TESTS=6
for i in 1 2 3 4 5 6
do
    DIFF=$(diff outputs/test$i.output <(./practica01 $i))
    
    if [ "$DIFF" != "" ]
    then
        echo "Prueba $i: FAIL"
        echo "$DIFF"
        ERRORS="$i"
    else
        echo "Prueba $i: PASS"
        COUNTER=$((COUNTER + 1))
    fi
done

echo "SUMMARY $COUNTER/$TOTAL_TESTS PASS"

if [ -z "$ERRORS" ] ;  then
    echo "TESTS SUCCEDED"
    exit 0
else
    echo "TESTS FAILED"
    exit -1
fi
